import * as THREE from 'three';
import { TERRAIN_NOISE_GLSL } from './terrainNoise.glsl.js';
import { terrainHeight } from './heightfield.js';
import {
  buildTerrainFragmentShader,
  buildTerrainVertexShader,
  selectTerrainStorage,
} from './terrain/material.glsl.js';

/**
 * Effectively infinite terrain, drawn as a GPU geometry clipmap.
 *
 * Layout
 * ------
 * LEVELS concentric square grids centred on the aircraft. Level 0 is a solid
 * block; levels 1..N-1 are hollow rings whose hole is exactly the footprint of
 * the level inside them. Each level's cell size doubles, so the whole stack is
 * a fixed triangle count regardless of how far you can see — about 1.03M on
 * the desktop default and 585k on medium, measured with __audit(). (The figure
 * here read 250k, which was four times under what the high tier submits.)
 *
 * Elevation
 * ---------
 * Each level owns one layer of a float texture array holding
 * (height, normal.xyz). Layers are regenerated by a fragment pass whenever the
 * level's snapped centre moves, which for the outer levels is almost never. The
 * vertex shader is then just two texture fetches — the 13-octave noise cost is
 * paid per *texel*, not per vertex, and never per frame for distant terrain.
 *
 * Seams
 * -----
 * CDLOD morphing. Toward its outer edge every level slides its odd vertices
 * onto the next level's grid and cross-fades to that level's heightmap, so by
 * the time a ring reaches its boundary it is bit-identical to the surface it
 * hands over to. No skirts, no popping, no cracks.
 */

/**
 * Clipmap grid resolution, in vertices per side.
 *
 * Mutable, and set once at boot before Terrain is constructed, because it is
 * the single biggest lever on both quality and cost and it cannot be changed
 * later: it fixes buffer sizes, render target dimensions and constants baked
 * into the shader source. Desktop wants 257 — measured free there, since this
 * renderer is fragment-bound — and a phone emphatically does not.
 *
 * Cell size at distance d is about d/HALF, so this is also the *only* knob
 * that controls how triangulated the range looks at range.
 */
let RES = 257;
let CELLS = RES - 1;
let HALF = CELLS / 2;
let HOLE = CELLS / 4 + 2;
let TEMP_RES = RES + 2;

/** Must be called before constructing Terrain; a no-op afterwards. */
export function configureTerrain({ res, levels }) {
  if (res) {
    RES = res;
    CELLS = RES - 1;
    HALF = CELLS / 2;
    HOLE = CELLS / 4 + 2;
    TEMP_RES = RES + 2;
  }
  if (levels) TERRAIN_LEVELS = levels;
}

/**
 * Where a ring's hole starts, in cell indices.
 *
 * The inner level occupies exactly indices [32, 96], so a hole of 32 looks
 * right — but each level snaps to its *own* grid (level L to 2·cellL, level L-1
 * to cellL), so their centres can sit up to 1.5 cells apart. A flush hole then
 * opens a gap on whichever side the centres drifted, which renders as a bright
 * hairline of sky snaking across the terrain. Overlapping the ring two cells
 * further in guarantees coverage; the fragment discard still trims it to the
 * exact boundary, so nothing is drawn twice.
 */

/** NDC depth nudge per clipmap level, so finer rings win inside the overlap. */
const DEPTH_BIAS = '1.2e-5';

export let TERRAIN_LEVELS = 10;
export const TERRAIN_BASE_CELL = 4.0;
export const CPU_TERRAIN_SAMPLE_BUDGET = 16384;

/** Half-extent, in metres, covered by the whole clipmap. */
export const terrainRadius = () => HALF * TERRAIN_BASE_CELL * 2 ** (TERRAIN_LEVELS - 1);

function buildGrid(skipHole) {
  const geometry = new THREE.InstancedBufferGeometry();

  const positions = new Float32Array(RES * RES * 3);
  let p = 0;
  for (let j = 0; j < RES; j++) {
    for (let i = 0; i < RES; i++) {
      positions[p++] = i;
      positions[p++] = 0;
      positions[p++] = j;
    }
  }
  geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));

  const indices = [];
  for (let j = 0; j < CELLS; j++) {
    for (let i = 0; i < CELLS; i++) {
      if (skipHole && i >= HOLE && i < CELLS - HOLE && j >= HOLE && j < CELLS - HOLE) continue;
      const a = j * RES + i;
      const b = a + 1;
      const c = a + RES;
      const d = c + 1;
      // Alternate the diagonal so ridgelines don't develop a directional bias.
      if ((i + j) & 1) indices.push(a, c, b, b, c, d);
      else indices.push(a, c, d, a, d, b);
    }
  }
  geometry.setIndex(indices);

  // Bounding sphere is meaningless here (vertices are grid indices displaced in
  // the shader), so culling is disabled on the meshes instead.
  geometry.boundingSphere = new THREE.Sphere(new THREE.Vector3(), Infinity);
  return geometry;
}

export class Terrain {
  constructor(renderer, environment) {
    this.renderer = renderer;
    this.environment = environment;

    this.floatLinear = renderer.extensions.has('OES_texture_float_linear');
    this.storage = selectTerrainStorage({
      colorFloat: renderer.extensions.has('EXT_color_buffer_float'),
      floatLinear: this.floatLinear,
    });
    this.cpuGenerated = !this.storage.gpuGenerated;
    this.cpuHeightData = this.cpuGenerated
      ? new Float32Array(RES * RES * TERRAIN_LEVELS * 4)
      : null;
    this.cpuLevelScratch = this.cpuGenerated ? new Float32Array(RES * RES) : null;
    this.cpuLayerStaging = this.cpuGenerated ? new Float32Array(RES * RES * 4) : null;
    this.cpuSampleBudget = CPU_TERRAIN_SAMPLE_BUDGET;
    this.cpuFrameStats = { samples: 0, commits: 0, uploadBytes: 0 };
    this._cpuJob = null;
    this._cpuNextLevel = 0;

    const filter = this.floatLinear ? THREE.LinearFilter : THREE.NearestFilter;

    if (this.cpuGenerated) {
      const texture = new THREE.DataArrayTexture(this.cpuHeightData, RES, RES, TERRAIN_LEVELS);
      texture.format = THREE.RGBAFormat;
      texture.type = THREE.FloatType;
      texture.minFilter = THREE.NearestFilter;
      texture.magFilter = THREE.NearestFilter;
      texture.wrapS = THREE.ClampToEdgeWrapping;
      texture.wrapT = THREE.ClampToEdgeWrapping;
      texture.generateMipmaps = false;
      this.heightArray = { texture, dispose: () => texture.dispose() };
    } else {
      this.heightArray = new THREE.WebGLArrayRenderTarget(RES, RES, TERRAIN_LEVELS, {
        format: THREE.RGBAFormat,
        type: THREE.FloatType,
        minFilter: filter,
        magFilter: filter,
        wrapS: THREE.ClampToEdgeWrapping,
        wrapT: THREE.ClampToEdgeWrapping,
        depthBuffer: false,
        stencilBuffer: false,
        generateMipmaps: false,
      });
    }

    this.tempTarget = new THREE.WebGLRenderTarget(TEMP_RES, TEMP_RES, {
      format: THREE.RedFormat,
      type: THREE.FloatType,
      minFilter: THREE.NearestFilter,
      magFilter: THREE.NearestFilter,
      depthBuffer: false,
      stencilBuffer: false,
      generateMipmaps: false,
    });

    /**
     * Staging target for the normal + shadow pass.
     *
     * That pass has to *read* the height array (to march shadow rays against
     * coarser levels) while producing the contents of one of its layers. Doing
     * both against the same texture is a framebuffer feedback loop — the driver
     * rejects the draw outright ("GL_INVALID_OPERATION: Feedback loop formed
     * between Framebuffer and active Texture") and the terrain disappears. So
     * the pass writes here, and a trivial blit copies it into the layer.
     */
    this.stageTarget = new THREE.WebGLRenderTarget(RES, RES, {
      format: THREE.RGBAFormat,
      type: THREE.FloatType,
      minFilter: THREE.NearestFilter,
      magFilter: THREE.NearestFilter,
      depthBuffer: false,
      stencilBuffer: false,
      generateMipmaps: false,
    });

    // Per-level state. `center` is what the heightmap layer currently holds;
    // `desired` is where it should be. They differ only while a regeneration is
    // queued, which keeps rendering consistent with the texture contents.
    this.cells = new Float32Array(TERRAIN_LEVELS);
    this.centers = [];
    this.desired = [];
    this.dirty = [];
    for (let L = 0; L < TERRAIN_LEVELS; L++) {
      this.cells[L] = TERRAIN_BASE_CELL * 2 ** L;
      this.centers.push(new THREE.Vector2(NaN, NaN));
      this.desired.push(new THREE.Vector2(0, 0));
      this.dirty.push(true);
    }
    this.centerArray = new Float32Array(TERRAIN_LEVELS * 2);

    this._buildGenerationPasses();
    this._buildTerrainMaterial();
    this.terrainQuality = 2;

    this.group = new THREE.Group();
    this.group.matrixAutoUpdate = false;

    const block = buildGrid(false);
    block.setAttribute('aLevel', new THREE.InstancedBufferAttribute(new Float32Array([0]), 1));
    block.instanceCount = 1;
    this.blockMesh = new THREE.Mesh(block, this.material);
    this.blockMesh.frustumCulled = false;
    this.blockMesh.renderOrder = 0;
    this.group.add(this.blockMesh);

    const ring = buildGrid(true);
    const levels = new Float32Array(TERRAIN_LEVELS - 1);
    for (let L = 1; L < TERRAIN_LEVELS; L++) levels[L - 1] = L;
    ring.setAttribute('aLevel', new THREE.InstancedBufferAttribute(levels, 1));
    ring.instanceCount = TERRAIN_LEVELS - 1;
    this.ringMesh = new THREE.Mesh(ring, this.material);
    this.ringMesh.frustumCulled = false;
    this.ringMesh.renderOrder = 0;
    this.group.add(this.ringMesh);

    this.triangleCount =
      (block.index.count + ring.index.count * (TERRAIN_LEVELS - 1)) / 3;
  }

  _buildGenerationPasses() {
    this.genScene = new THREE.Scene();
    this.genCamera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);

    const tri = new THREE.BufferGeometry();
    tri.setAttribute(
      'position',
      new THREE.BufferAttribute(new Float32Array([-1, -1, 0, 3, -1, 0, -1, 3, 0]), 3),
    );

    const vertexShader = /* glsl */ `
      void main() { gl_Position = vec4(position.xy, 0.0, 1.0); }
    `;

    this.heightPass = new THREE.ShaderMaterial({
      glslVersion: THREE.GLSL3,
      depthTest: false,
      depthWrite: false,
      uniforms: {
        uCenter: { value: new THREE.Vector2() },
        uCell: { value: 1 },
      },
      vertexShader,
      fragmentShader: /* glsl */ `
        precision highp float;
        uniform vec2 uCenter;
        uniform float uCell;
        out vec4 fragColor;
        ${TERRAIN_NOISE_GLSL}
        void main() {
          // One texel of margin on every side, so the normal pass can take
          // central differences without clamping at the border.
          vec2 idx = gl_FragCoord.xy - 0.5 - 1.0;
          vec2 world = uCenter + (idx - ${HALF.toFixed(1)}) * uCell;
          fragColor = vec4(t_height(world), 0.0, 0.0, 1.0);
        }
      `,
    });

    /**
     * Second generation pass: normals and sun visibility.
     *
     * Shadows are marched here, per heightmap texel, rather than per pixel in
     * the terrain shader. Two reasons. Cost — a texel is shaded once per
     * regeneration instead of every frame, and the far levels regenerate almost
     * never. And stability — a baked result is a pure function of world
     * position, so shadow edges do not crawl as the clipmap snaps.
     *
     * The march walks the heightmap array itself, one texture fetch per step
     * instead of fourteen octaves of noise, choosing the level whose extent
     * contains the sample. Softness uses iq's ray-marched penumbra estimate:
     * the closest approach to the terrain, scaled by distance travelled.
     *
     * Normals are stored as XZ only; Y is recovered as sqrt(1 - x² - z²), which
     * is exact for a heightfield and frees the alpha channel for visibility.
     */
    this.normalPass = new THREE.ShaderMaterial({
      glslVersion: THREE.GLSL3,
      depthTest: false,
      depthWrite: false,
      uniforms: {
        ...this.environment.uniforms,
        uHeights: { value: this.tempTarget.texture },
        uHeightArray: { value: this.heightArray.texture },
        uCenters: { value: this.centerArray },
        uCells: { value: this.cells },
        uCenter: { value: new THREE.Vector2() },
        uCell: { value: 1 },
        uTexel: { value: 1 / TEMP_RES },
        uLevel: { value: 0 },
        uShadowSteps: { value: 20 },
      },
      vertexShader,
      fragmentShader: /* glsl */ `
        precision highp float;
        precision highp sampler2DArray;

        uniform sampler2D uHeights;
        uniform sampler2DArray uHeightArray;
        uniform vec2 uCenters[${TERRAIN_LEVELS}];
        uniform float uCells[${TERRAIN_LEVELS}];
        uniform vec2 uCenter;
        uniform float uCell;
        uniform float uTexel;
        uniform int uLevel;
        uniform int uShadowSteps;
        uniform vec3 uSunDir;
        out vec4 fragColor;

        const float RES = ${RES.toFixed(1)};
        const float HALF = ${HALF.toFixed(1)};

        // Height from the coarsest-resolution level that still contains the
        // point. Returns a large negative value if nothing covers it, which the
        // caller treats as "no occluder".
        float arrayHeight(vec2 xz, float startLevel) {
          int L = int(clamp(startLevel, 0.0, float(${TERRAIN_LEVELS - 1})));
          for (int k = 0; k < 3; k++) {
            vec2 d = abs(xz - uCenters[L]);
            if (max(d.x, d.y) < uCells[L] * (HALF - 1.5)) {
              vec2 uv = ((xz - uCenters[L]) / uCells[L] + HALF + 0.5) / RES;
              return textureLod(uHeightArray, vec3(uv, float(L)), 0.0).r;
            }
            if (L >= ${TERRAIN_LEVELS - 1}) break;
            L++;
          }
          return -1.0e5;
        }

        // The level currently being generated is not in the array yet, so its
        // own heights come from the scratch target.
        float localHeight(vec2 xz) {
          vec2 idx = (xz - uCenter) / uCell + HALF + 1.0;
          if (min(idx.x, idx.y) < 0.5 || max(idx.x, idx.y) > ${(TEMP_RES - 1).toFixed(1)}) return -1.0e5;
          return textureLod(uHeights, (idx + 0.5) * uTexel, 0.0).r;
        }

        float sunVisibility(vec3 origin, vec3 normal, float ndl) {
          // Slope-scaled bias. A fixed offset is not enough: as the sun grazes
          // a face, one heightmap cell spans an ever-larger vertical drop, and
          // rays re-enter the surface they started on. That stipples sunlit
          // slopes with sawtooth acne that follows the mesh triangulation.
          // Scaling the lift by 1/ndl is the standard shadow-map remedy and it
          // is what actually clears it here.
          float slopeBias = uCell * (0.8 + 1.9 / max(ndl, 0.12));
          vec3 o = origin + normal * slopeBias;

          float t = uCell * 1.4;
          float vis = 1.0;
          for (int i = 0; i < 32; i++) {
            if (i >= uShadowSteps) break;
            vec3 p = o + uSunDir * t;
            // Nothing above the highest possible summit can be occluded.
            if (p.y > 7500.0) break;

            float h = localHeight(p.xz);
            if (h < -1.0e4) h = arrayHeight(p.xz, log2(max(t, 1.0) / 24.0));
            if (h < -1.0e4) break;

            // iq's ray-marched penumbra estimate: closest approach scaled by
            // distance travelled, so shadow edges sharpen near the occluder and
            // soften with range. Clamping instead of early-returning zero keeps
            // the transition continuous, which matters because this value is
            // then interpolated across triangles tens of metres wide.
            float diff = p.y - h;
            vis = min(vis, clamp(6.0 * diff / t + 0.04, 0.0, 1.0));
            if (vis <= 0.001) break;

            t *= 1.33;
            if (t > 40000.0) break;
          }
          return clamp(vis, 0.0, 1.0);
        }

        void main() {
          vec2 texel = gl_FragCoord.xy - 0.5;
          vec2 uv = (gl_FragCoord.xy + 1.0) * uTexel;
          float h  = texture(uHeights, uv).r;
          float hl = texture(uHeights, uv - vec2(uTexel, 0.0)).r;
          float hr = texture(uHeights, uv + vec2(uTexel, 0.0)).r;
          float hd = texture(uHeights, uv - vec2(0.0, uTexel)).r;
          float hu = texture(uHeights, uv + vec2(0.0, uTexel)).r;
          vec3 n = normalize(vec3(hl - hr, 2.0 * uCell, hd - hu));

          vec2 world = uCenter + (texel - HALF) * uCell;
          // Faces angled away from the sun are shadowed by their own geometry;
          // the N.L term already handles them, and marching adds only noise.
          // Fade the march in across the terminator rather than switching, or
          // the discontinuity shows up as a hard band in the ambient term.
          float ndl = dot(n, uSunDir);
          float vis = ndl <= 0.03
            ? 1.0
            : mix(1.0, sunVisibility(vec3(world.x, h, world.y), n, ndl), smoothstep(0.03, 0.16, ndl));

          fragColor = vec4(h, n.x, n.z, vis);
        }
      `,
    });

    this.blitPass = new THREE.ShaderMaterial({
      glslVersion: THREE.GLSL3,
      depthTest: false,
      depthWrite: false,
      uniforms: { uSource: { value: this.stageTarget.texture } },
      vertexShader,
      fragmentShader: /* glsl */ `
        precision highp float;
        uniform sampler2D uSource;
        out vec4 fragColor;
        void main() { fragColor = texelFetch(uSource, ivec2(gl_FragCoord.xy), 0); }
      `,
    });

    this.genQuad = new THREE.Mesh(tri, this.heightPass);
    this.genQuad.frustumCulled = false;
    this.genScene.add(this.genQuad);
  }

  _buildTerrainMaterial() {
    this.material = new THREE.ShaderMaterial({
      glslVersion: THREE.GLSL3,
      uniforms: {
        ...this.environment.uniforms,
        uHeightMap: { value: this.heightArray.texture },
        uCenters: { value: this.centerArray },
        uCells: { value: this.cells },
        uDetailFade: { value: 1.0 },
        // tan(defaultHalfFov) / tan(currentHalfFov); see the detail fade in
        // material.glsl.js. 1 unzoomed, about 4 in the recon optic.
        uZoomScale: { value: 1.0 },
      },
      vertexShader: buildTerrainVertexShader({
        levels: TERRAIN_LEVELS,
        res: RES,
        half: HALF,
        depthBias: DEPTH_BIAS,
      }),
      fragmentShader: buildTerrainFragmentShader({
        levels: TERRAIN_LEVELS,
        res: RES,
        half: HALF,
        quality: 2,
      }),
    });
  }

  /** Regenerate one clipmap layer's heightmap. */
  _generateLevel(L) {
    const renderer = this.renderer;
    const prevTarget = renderer.getRenderTarget();
    const prevAutoClear = renderer.autoClear;
    renderer.autoClear = false;

    const center = this.desired[L];
    const cell = this.cells[L];

    this.genQuad.material = this.heightPass;
    this.heightPass.uniforms.uCenter.value.copy(center);
    this.heightPass.uniforms.uCell.value = cell;
    renderer.setRenderTarget(this.tempTarget);
    renderer.render(this.genScene, this.genCamera);

    this.genQuad.material = this.normalPass;
    this.normalPass.uniforms.uCell.value = cell;
    this.normalPass.uniforms.uCenter.value.copy(center);
    this.normalPass.uniforms.uLevel.value = L;
    renderer.setRenderTarget(this.stageTarget);
    renderer.render(this.genScene, this.genCamera);

    this.genQuad.material = this.blitPass;
    renderer.setRenderTarget(this.heightArray, L);
    renderer.render(this.genScene, this.genCamera);

    renderer.setRenderTarget(prevTarget);
    renderer.autoClear = prevAutoClear;

    this.centers[L].copy(center);
    this.centerArray[L * 2] = center.x;
    this.centerArray[L * 2 + 1] = center.y;
    this.dirty[L] = false;
  }

  _beginCpuJob() {
    for (let offset = 0; offset < TERRAIN_LEVELS; offset++) {
      const L = (this._cpuNextLevel + offset) % TERRAIN_LEVELS;
      if (!this.dirty[L]) continue;
      this._cpuJob = {
        level: L,
        centerX: this.desired[L].x,
        centerZ: this.desired[L].y,
        phase: 0,
        cursor: 0,
      };
      this._cpuNextLevel = (L + 1) % TERRAIN_LEVELS;
      return true;
    }
    return false;
  }

  /** Advance one reusable CPU tile without exposing a partially updated layer. */
  _advanceCpuGeneration() {
    const stats = this.cpuFrameStats;
    stats.samples = 0;
    stats.commits = 0;
    stats.uploadBytes = 0;
    let remaining = Math.max(1, this.cpuSampleBudget | 0);
    if (!this._cpuJob && !this._beginCpuJob()) return 0;
    const job = this._cpuJob;
    const L = job.level;
    const cell = this.cells[L];
    const texelCount = RES * RES;

    while (remaining > 0 && job.phase === 0) {
      const start = job.cursor;
      const end = Math.min(start + remaining, texelCount);
      for (; job.cursor < end; job.cursor++) {
        const i = job.cursor % RES;
        const j = Math.floor(job.cursor / RES);
        const x = job.centerX + (i - HALF) * cell;
        const z = job.centerZ + (j - HALF) * cell;
        this.cpuLevelScratch[job.cursor] = terrainHeight(x, z);
      }
      const consumed = end - start;
      stats.samples += consumed;
      remaining -= consumed;
      if (job.cursor === texelCount) {
        job.phase = 1;
        job.cursor = 0;
      }
    }

    while (remaining > 0 && job.phase === 1 && job.cursor < texelCount) {
      const start = job.cursor;
      const end = Math.min(start + remaining, texelCount);
      for (; job.cursor < end; job.cursor++) {
        const i = job.cursor % RES;
        const j = Math.floor(job.cursor / RES);
        const left = this.cpuLevelScratch[j * RES + Math.max(i - 1, 0)];
        const right = this.cpuLevelScratch[j * RES + Math.min(i + 1, RES - 1)];
        const down = this.cpuLevelScratch[Math.max(j - 1, 0) * RES + i];
        const up = this.cpuLevelScratch[Math.min(j + 1, RES - 1) * RES + i];
        const gx = (right - left) / (Math.min(i + 1, RES - 1) - Math.max(i - 1, 0) || 1) / cell;
        const gz = (up - down) / (Math.min(j + 1, RES - 1) - Math.max(j - 1, 0) || 1) / cell;
        const invLength = 1 / Math.hypot(gx, 1, gz);
        const p = job.cursor * 4;
        this.cpuLayerStaging[p] = this.cpuLevelScratch[job.cursor];
        this.cpuLayerStaging[p + 1] = -gx * invLength;
        this.cpuLayerStaging[p + 2] = -gz * invLength;
        this.cpuLayerStaging[p + 3] = 1;
      }
      const consumed = end - start;
      stats.samples += consumed;
      remaining -= consumed;
    }

    if (job.phase === 1 && job.cursor === texelCount) {
      const layerOffset = L * texelCount * 4;
      this.cpuHeightData.set(this.cpuLayerStaging, layerOffset);
      this.heightArray.texture.addLayerUpdate(L);
      this.heightArray.texture.needsUpdate = true;
      this.centers[L].set(job.centerX, job.centerZ);
      this.centerArray[L * 2] = job.centerX;
      this.centerArray[L * 2 + 1] = job.centerZ;
      this.dirty[L] = this.desired[L].x !== job.centerX || this.desired[L].y !== job.centerZ;
      this._cpuJob = null;
      stats.commits = 1;
      stats.uploadBytes = this.cpuLayerStaging.byteLength;
      return 1;
    }
    return 0;
  }

  /**
   * @param {THREE.Vector3} focus  world position the clipmap should centre on
   * @param {number} budget        max layers to regenerate this frame
   */
  update(focus, budget = 4) {
    for (let L = 0; L < TERRAIN_LEVELS; L++) {
      const cell = this.cells[L];
      const snap = cell * 2;
      const cx = Math.round(focus.x / snap) * snap;
      const cz = Math.round(focus.z / snap) * snap;
      if (cx !== this.desired[L].x || cz !== this.desired[L].y) {
        this.desired[L].set(cx, cz);
        this.dirty[L] = true;
      }
    }

    if (this.cpuGenerated) return budget > 0 ? this._advanceCpuGeneration() : 0;

    let done = 0;
    for (let L = 0; L < TERRAIN_LEVELS && done < budget; L++) {
      if (this.dirty[L]) {
        this._generateLevel(L);
        done++;
      }
    }
    // Anything still dirty keeps its previous centre, so geometry and heightmap
    // never disagree; it simply lags by a frame or two at the coarse levels.
    return done;
  }

  /** Force every layer to be current. Used during loading. */
  prime(focus) {
    if (this.cpuGenerated) {
      for (let L = 0; L < TERRAIN_LEVELS; L++) {
        const snap = this.cells[L] * 2;
        this.desired[L].set(
          Math.round(focus.x / snap) * snap,
          Math.round(focus.z / snap) * snap,
        );
        this.dirty[L] = true;
      }
      this._cpuJob = null;
      // CPU fallback primes obey the same per-frame scheduler as flight
      // updates. The loading/title veil reveals complete layers progressively;
      // runtime primes keep sampling the prior centres until replacements land.
      return this._advanceCpuGeneration();
    }
    this.update(focus, TERRAIN_LEVELS);
  }

  /**
   * Read a clipmap layer back and compare it against whatever height function
   * the caller passes in. This is the check that keeps the GLSL and its JS
   * mirror honest — everything from ground collision to target placement is
   * wrong the moment they drift apart.
   *
   * Readback stalls the pipeline, so this is a diagnostic, never a per-frame path.
   */
  verifyAgainst(cpuHeight, level = 3) {
    let buffer;
    if (this.cpuGenerated) {
      const start = level * RES * RES * 4;
      buffer = this.cpuHeightData.subarray(start, start + RES * RES * 4);
    } else {
      buffer = new Float32Array(RES * RES * 4);
      // readRenderTargetPixels only honours its face/layer argument for cube
      // targets; for an array target it reads whichever layer is currently
      // attached. Bind the layer explicitly first.
      const prev = this.renderer.getRenderTarget();
      this.renderer.setRenderTarget(this.heightArray, level);
      this.renderer.readRenderTargetPixels(this.heightArray, 0, 0, RES, RES, buffer);
      this.renderer.setRenderTarget(prev);
    }

    const center = this.centers[level];
    const cell = this.cells[level];
    let maxError = 0;
    let sumError = 0;
    let worst = null;
    let n = 0;

    for (let j = 0; j < RES; j += 3) {
      for (let i = 0; i < RES; i += 3) {
        const gpu = buffer[(j * RES + i) * 4];
        const x = center.x + (i - HALF) * cell;
        const z = center.y + (j - HALF) * cell;
        const cpu = cpuHeight(x, z);
        const error = Math.abs(gpu - cpu);
        sumError += error;
        n++;
        if (error > maxError) {
          maxError = error;
          worst = { x, z, gpu, cpu };
        }
      }
    }

    return { level, samples: n, maxError, meanError: sumError / n, worst };
  }

  /**
   * How much narrower the current field of view is than the default.
   *
   * Procedural surface detail fades on world distance, which is right for the
   * chase camera and wrong for the recon optic: at a quarter of the field, a
   * ridge 4 km away subtends what a ridge 1 km away does, and fading its detail
   * anyway made the one photograph the sortie exists to take the least detailed
   * view in the game. Clamped, because the geometric clipmap resolution is
   * fixed at construction and there is no point promising detail the mesh
   * cannot carry.
   */
  setZoomScale(scale) {
    const clamped = Math.min(4, Math.max(1, Number.isFinite(scale) ? scale : 1));
    this.material.uniforms.uZoomScale.value = clamped;
  }

  setQuality(tier) {
    this.material.uniforms.uDetailFade.value = tier.terrainDetail;
    const quality = tier.name === 'high' ? 2 : tier.name === 'medium' ? 1 : 0;
    if (quality !== this.terrainQuality) {
      this.terrainQuality = quality;
      this.material.fragmentShader = buildTerrainFragmentShader({
        levels: TERRAIN_LEVELS,
        res: RES,
        half: HALF,
        quality,
      });
      this.material.needsUpdate = true;
    }
  }

  dispose() {
    this.heightArray.dispose();
    this.tempTarget.dispose();
    this.stageTarget.dispose();
    this.material.dispose();
    this.heightPass.dispose();
    this.normalPass.dispose();
    this.blitPass.dispose();
    this.blockMesh.geometry.dispose();
    this.ringMesh.geometry.dispose();
  }
}
