import * as THREE from 'three';
import { TERRAIN_NOISE_GLSL } from './terrainNoise.glsl.js';
import { ATMOSPHERE_GLSL, ATMOSPHERE_UNIFORMS_GLSL } from './atmosphere.glsl.js';

/**
 * Effectively infinite terrain, drawn as a GPU geometry clipmap.
 *
 * Layout
 * ------
 * LEVELS concentric square grids centred on the aircraft. Level 0 is a solid
 * block; levels 1..N-1 are hollow rings whose hole is exactly the footprint of
 * the level inside them. Each level's cell size doubles, so the whole stack is
 * a fixed 250k triangles regardless of how far you can see.
 *
 * Elevation
 * ---------
 * Each level owns one layer of a float texture array holding
 * (height, normal.xyz). Layers are regenerated by a fragment pass whenever the
 * level's snapped centre moves, which for the outer levels is almost never. The
 * vertex shader is then just two texture fetches — the 13-octave noise cost is
 * paid per *texel*, not per vertex, and never per frame for distant terrain.
 *
 * Seams
 * -----
 * CDLOD morphing. Toward its outer edge every level slides its odd vertices
 * onto the next level's grid and cross-fades to that level's heightmap, so by
 * the time a ring reaches its boundary it is bit-identical to the surface it
 * hands over to. No skirts, no popping, no cracks.
 */

const RES = 129; // vertices (and heightmap texels) per side
const CELLS = RES - 1; // 128
const HALF = CELLS / 2; // 64

/**
 * Where a ring's hole starts, in cell indices.
 *
 * The inner level occupies exactly indices [32, 96], so a hole of 32 looks
 * right — but each level snaps to its *own* grid (level L to 2·cellL, level L-1
 * to cellL), so their centres can sit up to 1.5 cells apart. A flush hole then
 * opens a gap on whichever side the centres drifted, which renders as a bright
 * hairline of sky snaking across the terrain. Overlapping the ring two cells
 * further in guarantees coverage; the fragment discard still trims it to the
 * exact boundary, so nothing is drawn twice.
 */
const HOLE = CELLS / 4 + 2; // 34
const TEMP_RES = RES + 2; // 1-texel margin so normals have valid neighbours

/** NDC depth nudge per clipmap level, so finer rings win inside the overlap. */
const DEPTH_BIAS = '1.2e-5';

export const TERRAIN_LEVELS = 11;
export const TERRAIN_BASE_CELL = 4.0;

/** Half-extent, in metres, covered by the whole clipmap. */
export const TERRAIN_RADIUS = HALF * TERRAIN_BASE_CELL * 2 ** (TERRAIN_LEVELS - 1);

function buildGrid(skipHole) {
  const geometry = new THREE.InstancedBufferGeometry();

  const positions = new Float32Array(RES * RES * 3);
  let p = 0;
  for (let j = 0; j < RES; j++) {
    for (let i = 0; i < RES; i++) {
      positions[p++] = i;
      positions[p++] = 0;
      positions[p++] = j;
    }
  }
  geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));

  const indices = [];
  for (let j = 0; j < CELLS; j++) {
    for (let i = 0; i < CELLS; i++) {
      if (skipHole && i >= HOLE && i < CELLS - HOLE && j >= HOLE && j < CELLS - HOLE) continue;
      const a = j * RES + i;
      const b = a + 1;
      const c = a + RES;
      const d = c + 1;
      // Alternate the diagonal so ridgelines don't develop a directional bias.
      if ((i + j) & 1) indices.push(a, c, b, b, c, d);
      else indices.push(a, c, d, a, d, b);
    }
  }
  geometry.setIndex(indices);

  // Bounding sphere is meaningless here (vertices are grid indices displaced in
  // the shader), so culling is disabled on the meshes instead.
  geometry.boundingSphere = new THREE.Sphere(new THREE.Vector3(), Infinity);
  return geometry;
}

export class Terrain {
  constructor(renderer, environment) {
    this.renderer = renderer;
    this.environment = environment;

    this.floatLinear = renderer.extensions.has('OES_texture_float_linear');
    if (!renderer.extensions.has('EXT_color_buffer_float')) {
      console.warn('[terrain] EXT_color_buffer_float missing; terrain will be degraded.');
    }

    const filter = this.floatLinear ? THREE.LinearFilter : THREE.NearestFilter;

    this.heightArray = new THREE.WebGLArrayRenderTarget(RES, RES, TERRAIN_LEVELS, {
      format: THREE.RGBAFormat,
      type: THREE.FloatType,
      minFilter: filter,
      magFilter: filter,
      wrapS: THREE.ClampToEdgeWrapping,
      wrapT: THREE.ClampToEdgeWrapping,
      depthBuffer: false,
      stencilBuffer: false,
      generateMipmaps: false,
    });

    this.tempTarget = new THREE.WebGLRenderTarget(TEMP_RES, TEMP_RES, {
      format: THREE.RedFormat,
      type: THREE.FloatType,
      minFilter: THREE.NearestFilter,
      magFilter: THREE.NearestFilter,
      depthBuffer: false,
      stencilBuffer: false,
      generateMipmaps: false,
    });

    /**
     * Staging target for the normal + shadow pass.
     *
     * That pass has to *read* the height array (to march shadow rays against
     * coarser levels) while producing the contents of one of its layers. Doing
     * both against the same texture is a framebuffer feedback loop — the driver
     * rejects the draw outright ("GL_INVALID_OPERATION: Feedback loop formed
     * between Framebuffer and active Texture") and the terrain disappears. So
     * the pass writes here, and a trivial blit copies it into the layer.
     */
    this.stageTarget = new THREE.WebGLRenderTarget(RES, RES, {
      format: THREE.RGBAFormat,
      type: THREE.FloatType,
      minFilter: THREE.NearestFilter,
      magFilter: THREE.NearestFilter,
      depthBuffer: false,
      stencilBuffer: false,
      generateMipmaps: false,
    });

    // Per-level state. `center` is what the heightmap layer currently holds;
    // `desired` is where it should be. They differ only while a regeneration is
    // queued, which keeps rendering consistent with the texture contents.
    this.cells = new Float32Array(TERRAIN_LEVELS);
    this.centers = [];
    this.desired = [];
    this.dirty = [];
    for (let L = 0; L < TERRAIN_LEVELS; L++) {
      this.cells[L] = TERRAIN_BASE_CELL * 2 ** L;
      this.centers.push(new THREE.Vector2(NaN, NaN));
      this.desired.push(new THREE.Vector2(0, 0));
      this.dirty.push(true);
    }
    this.centerArray = new Float32Array(TERRAIN_LEVELS * 2);

    this._buildGenerationPasses();
    this._buildTerrainMaterial();

    this.group = new THREE.Group();
    this.group.matrixAutoUpdate = false;

    const block = buildGrid(false);
    block.setAttribute('aLevel', new THREE.InstancedBufferAttribute(new Float32Array([0]), 1));
    block.instanceCount = 1;
    this.blockMesh = new THREE.Mesh(block, this.material);
    this.blockMesh.frustumCulled = false;
    this.blockMesh.renderOrder = 0;
    this.group.add(this.blockMesh);

    const ring = buildGrid(true);
    const levels = new Float32Array(TERRAIN_LEVELS - 1);
    for (let L = 1; L < TERRAIN_LEVELS; L++) levels[L - 1] = L;
    ring.setAttribute('aLevel', new THREE.InstancedBufferAttribute(levels, 1));
    ring.instanceCount = TERRAIN_LEVELS - 1;
    this.ringMesh = new THREE.Mesh(ring, this.material);
    this.ringMesh.frustumCulled = false;
    this.ringMesh.renderOrder = 0;
    this.group.add(this.ringMesh);

    this.triangleCount =
      (block.index.count + ring.index.count * (TERRAIN_LEVELS - 1)) / 3;
  }

  _buildGenerationPasses() {
    this.genScene = new THREE.Scene();
    this.genCamera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);

    const tri = new THREE.BufferGeometry();
    tri.setAttribute(
      'position',
      new THREE.BufferAttribute(new Float32Array([-1, -1, 0, 3, -1, 0, -1, 3, 0]), 3),
    );

    const vertexShader = /* glsl */ `
      void main() { gl_Position = vec4(position.xy, 0.0, 1.0); }
    `;

    this.heightPass = new THREE.ShaderMaterial({
      glslVersion: THREE.GLSL3,
      depthTest: false,
      depthWrite: false,
      uniforms: {
        uCenter: { value: new THREE.Vector2() },
        uCell: { value: 1 },
      },
      vertexShader,
      fragmentShader: /* glsl */ `
        precision highp float;
        uniform vec2 uCenter;
        uniform float uCell;
        out vec4 fragColor;
        ${TERRAIN_NOISE_GLSL}
        void main() {
          // One texel of margin on every side, so the normal pass can take
          // central differences without clamping at the border.
          vec2 idx = gl_FragCoord.xy - 0.5 - 1.0;
          vec2 world = uCenter + (idx - ${HALF.toFixed(1)}) * uCell;
          fragColor = vec4(t_height(world), 0.0, 0.0, 1.0);
        }
      `,
    });

    /**
     * Second generation pass: normals and sun visibility.
     *
     * Shadows are marched here, per heightmap texel, rather than per pixel in
     * the terrain shader. Two reasons. Cost — a texel is shaded once per
     * regeneration instead of every frame, and the far levels regenerate almost
     * never. And stability — a baked result is a pure function of world
     * position, so shadow edges do not crawl as the clipmap snaps.
     *
     * The march walks the heightmap array itself, one texture fetch per step
     * instead of fourteen octaves of noise, choosing the level whose extent
     * contains the sample. Softness uses iq's ray-marched penumbra estimate:
     * the closest approach to the terrain, scaled by distance travelled.
     *
     * Normals are stored as XZ only; Y is recovered as sqrt(1 - x² - z²), which
     * is exact for a heightfield and frees the alpha channel for visibility.
     */
    this.normalPass = new THREE.ShaderMaterial({
      glslVersion: THREE.GLSL3,
      depthTest: false,
      depthWrite: false,
      uniforms: {
        ...this.environment.uniforms,
        uHeights: { value: this.tempTarget.texture },
        uHeightArray: { value: this.heightArray.texture },
        uCenters: { value: this.centerArray },
        uCells: { value: this.cells },
        uCenter: { value: new THREE.Vector2() },
        uCell: { value: 1 },
        uTexel: { value: 1 / TEMP_RES },
        uLevel: { value: 0 },
        uShadowSteps: { value: 20 },
      },
      vertexShader,
      fragmentShader: /* glsl */ `
        precision highp float;
        precision highp sampler2DArray;

        uniform sampler2D uHeights;
        uniform sampler2DArray uHeightArray;
        uniform vec2 uCenters[${TERRAIN_LEVELS}];
        uniform float uCells[${TERRAIN_LEVELS}];
        uniform vec2 uCenter;
        uniform float uCell;
        uniform float uTexel;
        uniform int uLevel;
        uniform int uShadowSteps;
        uniform vec3 uSunDir;
        out vec4 fragColor;

        const float RES = ${RES.toFixed(1)};
        const float HALF = ${HALF.toFixed(1)};

        // Height from the coarsest-resolution level that still contains the
        // point. Returns a large negative value if nothing covers it, which the
        // caller treats as "no occluder".
        float arrayHeight(vec2 xz, float startLevel) {
          int L = int(clamp(startLevel, 0.0, float(${TERRAIN_LEVELS - 1})));
          for (int k = 0; k < 3; k++) {
            vec2 d = abs(xz - uCenters[L]);
            if (max(d.x, d.y) < uCells[L] * (HALF - 1.5)) {
              vec2 uv = ((xz - uCenters[L]) / uCells[L] + HALF + 0.5) / RES;
              return textureLod(uHeightArray, vec3(uv, float(L)), 0.0).r;
            }
            if (L >= ${TERRAIN_LEVELS - 1}) break;
            L++;
          }
          return -1.0e5;
        }

        // The level currently being generated is not in the array yet, so its
        // own heights come from the scratch target.
        float localHeight(vec2 xz) {
          vec2 idx = (xz - uCenter) / uCell + HALF + 1.0;
          if (min(idx.x, idx.y) < 0.5 || max(idx.x, idx.y) > ${(TEMP_RES - 1).toFixed(1)}) return -1.0e5;
          return texture(uHeights, (idx + 0.5) * uTexel).r;
        }

        float sunVisibility(vec3 origin, vec3 normal, float ndl) {
          // Slope-scaled bias. A fixed offset is not enough: as the sun grazes
          // a face, one heightmap cell spans an ever-larger vertical drop, and
          // rays re-enter the surface they started on. That stipples sunlit
          // slopes with sawtooth acne that follows the mesh triangulation.
          // Scaling the lift by 1/ndl is the standard shadow-map remedy and it
          // is what actually clears it here.
          float slopeBias = uCell * (0.8 + 1.9 / max(ndl, 0.12));
          vec3 o = origin + normal * slopeBias;

          float t = uCell * 1.4;
          float vis = 1.0;
          for (int i = 0; i < 32; i++) {
            if (i >= uShadowSteps) break;
            vec3 p = o + uSunDir * t;
            // Nothing above the highest possible summit can be occluded.
            if (p.y > 7500.0) break;

            float h = localHeight(p.xz);
            if (h < -1.0e4) h = arrayHeight(p.xz, log2(max(t, 1.0) / 24.0));
            if (h < -1.0e4) break;

            // iq's ray-marched penumbra estimate: closest approach scaled by
            // distance travelled, so shadow edges sharpen near the occluder and
            // soften with range. Clamping instead of early-returning zero keeps
            // the transition continuous, which matters because this value is
            // then interpolated across triangles tens of metres wide.
            float diff = p.y - h;
            vis = min(vis, clamp(6.0 * diff / t + 0.04, 0.0, 1.0));
            if (vis <= 0.001) break;

            t *= 1.33;
            if (t > 40000.0) break;
          }
          return clamp(vis, 0.0, 1.0);
        }

        void main() {
          vec2 texel = gl_FragCoord.xy - 0.5;
          vec2 uv = (gl_FragCoord.xy + 1.0) * uTexel;
          float h  = texture(uHeights, uv).r;
          float hl = texture(uHeights, uv - vec2(uTexel, 0.0)).r;
          float hr = texture(uHeights, uv + vec2(uTexel, 0.0)).r;
          float hd = texture(uHeights, uv - vec2(0.0, uTexel)).r;
          float hu = texture(uHeights, uv + vec2(0.0, uTexel)).r;
          vec3 n = normalize(vec3(hl - hr, 2.0 * uCell, hd - hu));

          vec2 world = uCenter + (texel - HALF) * uCell;
          // Faces angled away from the sun are shadowed by their own geometry;
          // the N.L term already handles them, and marching adds only noise.
          // Fade the march in across the terminator rather than switching, or
          // the discontinuity shows up as a hard band in the ambient term.
          float ndl = dot(n, uSunDir);
          float vis = ndl <= 0.03
            ? 1.0
            : mix(1.0, sunVisibility(vec3(world.x, h, world.y), n, ndl), smoothstep(0.03, 0.16, ndl));

          fragColor = vec4(h, n.x, n.z, vis);
        }
      `,
    });

    this.blitPass = new THREE.ShaderMaterial({
      glslVersion: THREE.GLSL3,
      depthTest: false,
      depthWrite: false,
      uniforms: { uSource: { value: this.stageTarget.texture } },
      vertexShader,
      fragmentShader: /* glsl */ `
        precision highp float;
        uniform sampler2D uSource;
        out vec4 fragColor;
        void main() { fragColor = texelFetch(uSource, ivec2(gl_FragCoord.xy), 0); }
      `,
    });

    this.genQuad = new THREE.Mesh(tri, this.heightPass);
    this.genQuad.frustumCulled = false;
    this.genScene.add(this.genQuad);
  }

  _buildTerrainMaterial() {
    this.material = new THREE.ShaderMaterial({
      glslVersion: THREE.GLSL3,
      uniforms: {
        ...this.environment.uniforms,
        uHeightMap: { value: this.heightArray.texture },
        uCenters: { value: this.centerArray },
        uCells: { value: this.cells },
        uDetailFade: { value: 1.0 },
      },
      vertexShader: /* glsl */ `
        precision highp float;
        precision highp sampler2DArray;

        in float aLevel;

        uniform sampler2DArray uHeightMap;
        uniform vec2 uCenters[${TERRAIN_LEVELS}];
        uniform float uCells[${TERRAIN_LEVELS}];

        out vec3 vWorld;
        out float vMorph;
        flat out int vLevel;
        flat out int vNextLevel;

        const float RES = ${RES.toFixed(1)};
        const float HALF = ${HALF.toFixed(1)};

        vec2 levelUV(vec2 world, int L) {
          return ((world - uCenters[L]) / uCells[L] + HALF + 0.5) / RES;
        }

        void main() {
          int L = int(aLevel + 0.5);
          int Ln = min(L + 1, ${TERRAIN_LEVELS - 1});
          float cell = uCells[L];
          vec2 center = uCenters[L];

          vec2 idx = position.xz;

          // Chebyshev distance to the level centre, normalised so the level's
          // own boundary is 1.0.
          vec2 d = abs(idx - HALF) / HALF;
          float m = max(d.x, d.y);
          float k = (L == ${TERRAIN_LEVELS - 1}) ? 0.0 : smoothstep(0.70, 0.94, m);

          // Slide odd vertices onto the next level's grid.
          vec2 odd = fract(idx * 0.5) * 2.0;
          vec2 morphIdx = idx - odd * k;
          vec2 world = center + (morphIdx - HALF) * cell;

          float h0 = textureLod(uHeightMap, vec3(levelUV(world, L), float(L)), 0.0).r;
          float h1 = textureLod(uHeightMap, vec3(levelUV(world, Ln), float(Ln)), 0.0).r;
          float h = mix(h0, h1, k);

          vWorld = vec3(world.x, h, world.y);
          vMorph = k;
          vLevel = L;
          vNextLevel = Ln;

          gl_Position = projectionMatrix * modelViewMatrix * vec4(vWorld, 1.0);

          // Rings overlap their inner neighbour by two cells (see HOLE). Rather
          // than discarding the overlap in the fragment shader — which costs
          // early-Z and made all eleven levels shade every pixel, dropping the
          // frame rate to 20 — nudge coarser levels away in depth so the finer
          // one simply wins. Inside the band both levels are fully morphed to
          // the same surface, so there is nothing visible to choose between.
          gl_Position.z += gl_Position.w * ${DEPTH_BIAS} * float(L);
        }
      `,
      fragmentShader: /* glsl */ `
        precision highp float;
        precision highp sampler2DArray;

        in vec3 vWorld;
        in float vMorph;
        flat in int vLevel;
        flat in int vNextLevel;

        out vec4 fragColor;

        uniform sampler2DArray uHeightMap;
        uniform vec2 uCenters[${TERRAIN_LEVELS}];
        uniform float uCells[${TERRAIN_LEVELS}];
        uniform float uDetailFade;
        uniform float uTime;
        uniform vec2 uWind;
        uniform float uCloudCover;
        uniform float uCloudScale;
        uniform float uCloudShadowStrength;
        uniform vec3 uCameraPos;
        ${ATMOSPHERE_UNIFORMS_GLSL}
        ${ATMOSPHERE_GLSL}

        const float RES = ${RES.toFixed(1)};
        const float HALF = ${HALF.toFixed(1)};

        vec2 levelUV(vec2 world, int L) {
          return ((world - uCenters[L]) / uCells[L] + HALF + 0.5) / RES;
        }

        float hash21(vec2 p) {
          p = 50.0 * fract(p * 0.3183099 + vec2(0.71, 0.113));
          return -1.0 + 2.0 * fract(p.x * p.y * (p.x + p.y));
        }

        float vnoise(vec2 x) {
          vec2 p = floor(x), f = fract(x);
          vec2 u = f * f * (3.0 - 2.0 * f);
          return mix(mix(hash21(p), hash21(p + vec2(1, 0)), u.x),
                     mix(hash21(p + vec2(0, 1)), hash21(p + vec2(1, 1)), u.x), u.y);
        }

        // Same noise with analytic derivatives, so the close-range detail bump
        // costs one evaluation instead of four finite differences.
        vec3 vnoised(vec2 x) {
          vec2 p = floor(x), f = fract(x);
          vec2 u = f * f * (3.0 - 2.0 * f);
          vec2 du = 6.0 * f * (1.0 - f);
          float a = hash21(p);
          float b = hash21(p + vec2(1, 0));
          float c = hash21(p + vec2(0, 1));
          float d = hash21(p + vec2(1, 1));
          float k1 = b - a, k2 = c - a, k3 = a - b - c + d;
          return vec3(a + k1 * u.x + k2 * u.y + k3 * u.x * u.y,
                      du.x * (k1 + k3 * u.y),
                      du.y * (k2 + k3 * u.x));
        }

        float fbm2(vec2 p, int oct) {
          float v = 0.0, a = 0.5;
          for (int i = 0; i < 6; i++) {
            if (i >= oct) break;
            v += a * vnoise(p);
            p = mat2(1.6, 1.2, -1.2, 1.6) * p;
            a *= 0.5;
          }
          return v;
        }

        // Shadows cast by the cloud layer. Projected along the sun direction so
        // they slide across ridges correctly rather than lying flat on the map.
        float cloudShadow(vec3 world) {
          float layerY = 6400.0;
          float t = (layerY - world.y) / max(uSunDir.y, 0.15);
          vec2 p = (world.xz + uSunDir.xz * t) * uCloudScale + uWind * uTime * 0.00006;
          float n = fbm2(p * 3.0, 3) * 0.5 + 0.5;
          float cov = smoothstep(0.62 - uCloudCover * 0.45, 0.86 - uCloudCover * 0.32, n);
          return 1.0 - uCloudShadowStrength * cov;
        }

        void main() {
          // Layout is (height, normal.x, normal.z, sun visibility). Normal Y is
          // recovered rather than stored — it is always positive on a
          // heightfield — which buys the alpha channel for baked shadows.
          vec4 s0 = texture(uHeightMap, vec3(levelUV(vWorld.xz, vLevel), float(vLevel)));
          vec4 s1 = texture(uHeightMap, vec3(levelUV(vWorld.xz, vNextLevel), float(vNextLevel)));
          vec4 s = mix(s0, s1, vMorph);
          vec3 macroN = normalize(vec3(s.g, sqrt(max(1.0 - s.g * s.g - s.b * s.b, 1e-4)), s.b));
          vec3 N = macroN;
          float sunVis = s.a;

          vec3 toCam = uCameraPos - vWorld;
          float dist = length(toCam);
          vec3 viewDir = -toCam / dist;

          // Close-range detail bump, from the analytic gradient of a two-octave
          // field rather than four finite-difference fbm evaluations.
          //
          // Each octave fades at its own distance rather than both together.
          // The limit is when an octave's period approaches a pixel, and the two
          // are 9 m and 23 m, so they reach it a long way apart: fading both by
          // 1.1 km threw away the coarse one while it was still resolved by a
          // wide margin. That mattered most at recon range, where a ridge 1.5 km
          // out is drawn with 32 m cells — about 20 pixels a triangle — and read
          // as flat shaded facets in every photograph.
          float detailFine = uDetailFade * (1.0 - smoothstep(220.0, 900.0, dist));
          float detailCoarse = uDetailFade * (1.0 - smoothstep(850.0, 3000.0, dist));
          if (detailFine + detailCoarse > 0.002) {
            vec2 grad = vec2(0.0);
            if (detailFine > 0.002) {
              grad += vnoised(vWorld.xz * 0.115).yz * (0.115 * 0.55 * detailFine);
            }
            if (detailCoarse > 0.002) {
              grad += vnoised(vWorld.xz * 0.043 + 17.0).yz * (0.043 * 1.35 * detailCoarse);
            }
            N = normalize(N + vec3(-grad.x, 0.0, -grad.y) * 9.0);
          }

          // Steepness for the material mix, corrected for LOD.
          //
          // The stored normal is a central difference over this level's cell, so
          // the steepness it reports collapses as cells grow. Measured against
          // this terrain's own height function, the median gradient falls from
          // 1.23 at 8 m sampling to 0.41 at 512 m, and the fraction of ground
          // steeper than 0.54 goes from 25% to essentially nothing. Mixing the
          // material straight off that normal is what painted every range in the
          // middle distance solid white: the shader was asking how steep the
          // ground is and being told, correctly, that a 500 m average is gentle.
          //
          // Fractal terrain has a well-defined gradient scaling exponent, so one
          // per-level factor fixes it without storing a second surface. The
          // exponent was measured rather than assumed: g(eps) ~ eps^-0.25 held
          // to within a few percent from 16 m out to 2 km, and rescaling by
          // (cell/8)^0.25 reproduces the 8 m slope distribution at every level.
          // Interpolating the factor across the morph band keeps the material
          // continuous where two levels meet.
          //
          // Taken from the macro normal, before the detail bump. The bump is a
          // decorative high-frequency perturbation for shading; feeding it into
          // the material pushed patches of ordinary snowfield over the rock
          // threshold and mottled whole faces into something like camouflage.
          //
          // Lighting keeps the uncorrected normal for the opposite reason: it
          // has to match the geometry actually on screen, and a fine-scale
          // normal at 30 km would alias into noise.
          float matCell = mix(uCells[vLevel], uCells[vNextLevel], vMorph);
          vec2 matGrad =
            vec2(macroN.x, macroN.z) / max(macroN.y, 1e-3) * pow(matCell * 0.125, 0.25);
          float slope = clamp(1.0 - inversesqrt(1.0 + dot(matGrad, matGrad)), 0.0, 1.0);
          float h = vWorld.y;

          float rough = vnoise(vWorld.xz * 0.0016) * 0.62 + vnoise(vWorld.xz * 0.0041) * 0.3;
          float band = fbm2(vWorld.xz * 0.00042, 2);

          // ---- surface mix -------------------------------------------------
          // Ladakh rock is dark grey-brown, not desert tan: steep faces are
          // near-black shale, and the gentler ground is grey scree with a faint
          // iron stain. Keeping albedo genuinely low is what lets snow read as
          // brilliant by comparison.
          vec3 rockDark  = vec3(0.040, 0.038, 0.038);
          vec3 rockLight = vec3(0.093, 0.082, 0.070);
          vec3 rock = mix(rockDark, rockLight, clamp(0.5 + 0.7 * rough, 0.0, 1.0));
          rock = mix(rock, vec3(0.115, 0.090, 0.066), smoothstep(0.1, 0.6, band) * 0.55);

          // Bedding planes. Himalayan rock is strongly banded, and those bands
          // are the main thing that reads as *stone* at close range rather than
          // as a brown surface with noise on it. Far Cry 5's terrain talk
          // extrudes strata of varying thickness; the analytic equivalent is a
          // sawtooth through a slightly tilted plane, domain-warped so the beds
          // are not mathematically straight.
          //
          // They earn their cost twice. Perceived self-motion tracks *edge
          // rate* -- how many discontinuities cross the eye per second -- more
          // strongly than smooth optical flow does (Larish & Flach, 1990), and
          // smooth gradient noise contributes nothing to that while hard edges
          // do. This is the cheapest sense-of-speed cue available to a renderer
          // whose whole world is analytic.
          //
          // Band-limited on the screen-space derivative of the bedding
          // coordinate: once a pixel spans a large fraction of one bed the
          // pattern is past Nyquist and has to fade to its average, or it
          // crawls and sparkles at exactly the distances a jet spends its time.
          // The dip direction rotates from massif to massif, and that is not a
          // flourish. A single global bedding plane that is nearly horizontal
          // makes dot(worldPos, planeNormal) track elevation, so every band
          // follows a contour and the range reads as a topographic map rather
          // than as rock. Giving each region its own strike and a genuine dip
          // breaks that, which is also what real folded terrain does. Bed
          // thickness varies with the same roughness field.
          float dipAngle = vnoise(vWorld.xz * 0.00013) * 6.2832;
          vec3 bedNormal = normalize(vec3(cos(dipAngle) * 0.55, 1.0, sin(dipAngle) * 0.55));
          float bedding = dot(vWorld, bedNormal) / (17.0 + 24.0 * abs(rough))
                        + vnoise(vWorld.xz * 0.0011) * 3.1;
          float bedFade = (1.0 - smoothstep(0.20, 0.72, fwidth(bedding))) * uDetailFade;
          vec3 scree = mix(vec3(0.096, 0.089, 0.081), vec3(0.142, 0.128, 0.110), rough * 0.5 + 0.5);
          if (bedFade > 0.004) {
            float f = fract(bedding);
            float edge = smoothstep(0.0, 0.10, f) * smoothstep(1.0, 0.90, f);
            float tone = vnoise(vec2(floor(bedding) * 1.7, 3.3));
            float strata = 1.0 + bedFade * ((tone - 0.5) * 0.44 - (1.0 - edge) * 0.30);
            rock *= strata;
            scree *= mix(1.0, strata, 0.35); // scree is loose, so only faintly bedded
          }

          float screeAmt = 1.0 - smoothstep(0.16, 0.46, slope);
          vec3 ground = mix(rock, scree, clamp(screeAmt, 0.0, 1.0));

          // ---- snow --------------------------------------------------------
          float snowLine = 4450.0 + 620.0 * band + 210.0 * rough;
          float snow = smoothstep(snowLine - 700.0, snowLine + 280.0, h);
          // Snow does not hold on steep faces. In the Dras and Kargil sectors
          // that threshold is low — anything past roughly 35 degrees is barren
          // rock and scree — and it is precisely that exposed structure which
          // gives the range its geology instead of a smooth white dome.
          snow *= 1.0 - smoothstep(0.20, 0.54, slope);
          // Break the snow line into patches rather than a drawn contour.
          //
          // This term used to add 0.9 * rough * snow * (1-snow) * 4.0, whose
          // effective coefficient of 3.6 saturated snow to 1.0 for any positive
          // rough. Since rough is roughly symmetric about zero, that erased the
          // slope relationship over half the map and the whole range read as
          // poured cream. It is a perturbation, so it stays bounded well under
          // the signal, and peaks where the mix is genuinely ambiguous.
          snow = clamp(snow + rough * 0.30 * (1.0 - abs(2.0 * snow - 1.0)), 0.0, 1.0);

          // Wind-blown drifts collect in the lee of gullies at any altitude.
          float drift = smoothstep(0.42, 0.05, slope) * smoothstep(3900.0, 4700.0, h);
          snow = max(snow, drift * 0.5 * smoothstep(-0.15, 0.35, band));

          vec3 snowCol = vec3(0.74, 0.775, 0.85);
          vec3 albedo = mix(ground, snowCol, snow);

          // ---- lighting ----------------------------------------------------
          float ndl = dot(N, uSunDir);
          // Cast shadow never goes fully black: high-altitude air scatters a
          // little direct sun sideways, and a hard zero reads as a hole.
          float shadow = cloudShadow(vWorld) * mix(0.12, 1.0, sunVis);
          // Snow scatters light forward through its top layer, so it stays lit
          // a little past the terminator. Kept modest: too much wrap and the
          // peaks lose all their shape and read as poured cream.
          float wrapped = pow(clamp(ndl * 0.5 + 0.5, 0.0, 1.0), 2.4);
          float lambert = max(ndl, 0.0);
          float diffuse = mix(lambert, wrapped, snow * 0.35) * shadow;

          // Sky illumination. A shadowed snowfield at 6 km is lit by the entire
          // dome and by bounce off every lit face around it, so it stays a
          // bright cold blue — nothing like the near-black an unlit surface
          // would suggest. Getting this term too low is what makes procedural
          // snow read as grey plastic.
          vec3 skyUp = uZenithColor * 1.5 + vec3(0.10, 0.16, 0.26);
          vec3 bounce = mix(vec3(0.12, 0.115, 0.112), vec3(0.52, 0.58, 0.68), snow);
          vec3 ambient =
            mix(bounce, skyUp, clamp(N.y * 0.5 + 0.5, 0.0, 1.0)) * 0.62 * (0.80 + 0.20 * sunVis);

          // No per-channel penumbra tint here, though it is the standard trick
          // (iq, Outdoors Lighting). Raising diffuse to per-channel powers
          // above 1 reduces the sun term everywhere it is not saturated, which
          // let the blue sky ambient dominate and pulled the whole range cold
          // and murky — it undid the ambient balance that was tuned to stop
          // shadowed snow crushing to grey. The blue-shadow cue it exists to
          // produce is already carried by the sky term below.
          vec3 color = albedo * (uSunColor * uSunIntensity * diffuse + ambient);

          // Specular glint off wind-packed snow.
          if (snow > 0.02) {
            vec3 H = normalize(uSunDir - viewDir);
            float spec = pow(max(dot(N, H), 0.0), 56.0);
            color += uSunColor * spec * snow * 0.4 * shadow;
          }

          color = atm_applyAerial(color, viewDir, dist, uCameraPos.y, vWorld.y);
          fragColor = vec4(color, 1.0);
        }
      `,
    });
  }

  /** Regenerate one clipmap layer's heightmap. */
  _generateLevel(L) {
    const renderer = this.renderer;
    const prevTarget = renderer.getRenderTarget();
    const prevAutoClear = renderer.autoClear;
    renderer.autoClear = false;

    const center = this.desired[L];
    const cell = this.cells[L];

    this.genQuad.material = this.heightPass;
    this.heightPass.uniforms.uCenter.value.copy(center);
    this.heightPass.uniforms.uCell.value = cell;
    renderer.setRenderTarget(this.tempTarget);
    renderer.render(this.genScene, this.genCamera);

    this.genQuad.material = this.normalPass;
    this.normalPass.uniforms.uCell.value = cell;
    this.normalPass.uniforms.uCenter.value.copy(center);
    this.normalPass.uniforms.uLevel.value = L;
    renderer.setRenderTarget(this.stageTarget);
    renderer.render(this.genScene, this.genCamera);

    this.genQuad.material = this.blitPass;
    renderer.setRenderTarget(this.heightArray, L);
    renderer.render(this.genScene, this.genCamera);

    renderer.setRenderTarget(prevTarget);
    renderer.autoClear = prevAutoClear;

    this.centers[L].copy(center);
    this.centerArray[L * 2] = center.x;
    this.centerArray[L * 2 + 1] = center.y;
    this.dirty[L] = false;
  }

  /**
   * @param {THREE.Vector3} focus  world position the clipmap should centre on
   * @param {number} budget        max layers to regenerate this frame
   */
  update(focus, budget = 4) {
    for (let L = 0; L < TERRAIN_LEVELS; L++) {
      const cell = this.cells[L];
      const snap = cell * 2;
      const cx = Math.round(focus.x / snap) * snap;
      const cz = Math.round(focus.z / snap) * snap;
      if (cx !== this.desired[L].x || cz !== this.desired[L].y) {
        this.desired[L].set(cx, cz);
        this.dirty[L] = true;
      }
    }

    let done = 0;
    for (let L = 0; L < TERRAIN_LEVELS && done < budget; L++) {
      if (this.dirty[L]) {
        this._generateLevel(L);
        done++;
      }
    }
    // Anything still dirty keeps its previous centre, so geometry and heightmap
    // never disagree; it simply lags by a frame or two at the coarse levels.
    return done;
  }

  /** Force every layer to be current. Used during loading. */
  prime(focus) {
    this.update(focus, TERRAIN_LEVELS);
  }

  /**
   * Read a clipmap layer back and compare it against whatever height function
   * the caller passes in. This is the check that keeps the GLSL and its JS
   * mirror honest — everything from ground collision to target placement is
   * wrong the moment they drift apart.
   *
   * Readback stalls the pipeline, so this is a diagnostic, never a per-frame path.
   */
  verifyAgainst(cpuHeight, level = 3) {
    const buffer = new Float32Array(RES * RES * 4);
    // readRenderTargetPixels only honours its face/layer argument for cube
    // targets; for an array target it reads whichever layer is currently
    // attached. Bind the layer explicitly first.
    const prev = this.renderer.getRenderTarget();
    this.renderer.setRenderTarget(this.heightArray, level);
    this.renderer.readRenderTargetPixels(this.heightArray, 0, 0, RES, RES, buffer);
    this.renderer.setRenderTarget(prev);

    const center = this.centers[level];
    const cell = this.cells[level];
    let maxError = 0;
    let sumError = 0;
    let worst = null;
    let n = 0;

    for (let j = 0; j < RES; j += 3) {
      for (let i = 0; i < RES; i += 3) {
        const gpu = buffer[(j * RES + i) * 4];
        const x = center.x + (i - HALF) * cell;
        const z = center.y + (j - HALF) * cell;
        const cpu = cpuHeight(x, z);
        const error = Math.abs(gpu - cpu);
        sumError += error;
        n++;
        if (error > maxError) {
          maxError = error;
          worst = { x, z, gpu, cpu };
        }
      }
    }

    return { level, samples: n, maxError, meanError: sumError / n, worst };
  }

  setQuality(tier) {
    this.material.uniforms.uDetailFade.value = tier.terrainDetail;
  }

  dispose() {
    this.heightArray.dispose();
    this.tempTarget.dispose();
    this.stageTarget.dispose();
    this.material.dispose();
    this.heightPass.dispose();
    this.normalPass.dispose();
    this.blitPass.dispose();
    this.blockMesh.geometry.dispose();
    this.ringMesh.geometry.dispose();
  }
}
